sudo: true
language: node_js
node_js:
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'
os:
- linux
- osx
fast_finish: true
addons:
  apt:
    packages:
    - libc6-i386
    - lib32stdc++6
    - zlib1g:i386
    - squid
    - apache2-utils
    - jq

install: 'npm install --ignore-scripts'
script:
- npm run lint
- npm run test
- node install.js
- ./acceptance.sh
env:
  global:
  - secure: rriEkfYzHxGmvHCjHluUwayDbBMP8xnSoWUjycdtBUn7EUnP/xxc2DNDhPo5NZylPQ3Hqab8JvyqJBwoHJSMoXSHvJSJAhzUF5a0XyaWV7CKH08SaNekyQQnRyuNq7KulyNYuhE7OrJkdX8O5QMiu9L7x7j6lbiMEukzaCWNfBxsdhAc+ZMMV/nCUHS4iDH7Ob2jGzM0qqgwXHpuEAlPClvAK3wYqyjQqhrSjVMqJ3gjeVYbTstTDHMJsW0P83LWHatuGQWYrWD2/0Jqn7r24f5pAsP+/Y3cSKa3CZiyAAm4p9r1GkhqMvINmFt30iv2ja6Ymp89o4VueOURiR6b0nCNxSgAdr39TN//f4XH1WbXT0IBHQcyLJe2NcmcI0ynY1plksPnrERHlh8wKw+4sNo21/POFX0aa3gfbiLtl8mJ4w+MzCbJ/kabvpkxo3LH9LP0IAKPY/6Zw8Zrx5FNXVhtYYSC5YviGspVJkbFDkd51cQk0U56xt+L5HW08to3uYyX1MfNIyYQ1OK6RZxFD4ShY+4HO9mDbaUfqTUqKG14YK0ZRFKG5S3R+AeV/ftnNYssG08XrPILF5FvP2wDSZQ8zOa1VGlzB7PUOt2jl/qYzu0fqvfCykdxbMkTDj7Z6l8bhlT8SaoQMYtTfyvjdqSybSCU2h2Dc9nBV/I0D4c=
  - secure: eUTPqpgi2K+atCkm4qicDj6Uglo2SCTsGexENXwO5KBJD56pK1rumDHhiOdZPd3bRpxyqnVXIPxxRdRx8R1aZMi2CcrPUPY5zYLI2ZeITu3naIauHNNRasX7aFvtm7ISReR2oR5i5sZy8gdPIstVPcZgW69AIvOycmb8JttoSL9AiPe5s5YgU/ps2LICF/Iq5ZoTHy9zGbYzIJtIXdRjKZchCqiNK7pFydWUxxzIUmc8jhNR32xT4YbFXL+zzRKnlg1SlFj3x+YSedPU2VTH0engfPzS1RTkWoqDjn8fqx6y2ZaZgKWtCRYIKFwcCJKMXlI9rZxm1WHxKNz6cU+fzyLgTyBcbjExdOxxEFvI2g6y/uo3Tbyy3KWot8WVlDZYiinX/69jd6Bhq6RZFJn2CeC+a47ldDdSbmXhQKmqWMuR3vzQxiVgek/+d9wz8suSn7QPAcXa7kPihKrjTU+ucl25iMYbLfETlHsk8tEPi+8hfiFKCqG+A6hqX+uLNptDJNjfiokNnPqGtaKF0QnMX3Fs7MGn5fDb8zqE0kJYfkGmElV9cdfVAkOBAmIf1BYcb7EQ0HmCRg/k/1tDZ1bpW/nVTJiGiX2TnXeHiu1nfsKr71ExJdpxwH0lN+OoZlM8KIagZZMZFzq204XMgaQsonZu4qpYUT1XkKYrDe50lyA=
  - secure: ggX+06Zv5wFHwoKQpEaxXhbJCf/jmmWfDDkon1HwgTbSwKDLju50jXQUx9JS1OIp7V1bndJZ9x8Av1MhA0krpFn8jBhx3/mHlcmwhjtCz4SudPlDS3o3NBV2lgoFEGroRBZ3i5KQNtzqGwq8dSyWPTPyFZLdS4QGMegyZveonavA9cZARaD9hfi5mabQs2ZxEgEug5vBk2UIRgjH4E/Ef+zEAwcl6qP06a2K/0/Y2RxLeBlbUkKkTyObePuc5ZvRevxDyuhWEAXEJWbZ8WjkyE322ugW6iiDqDP56PcH5k/m/NIDMP0N+qVKQ8VRvqADK1VPDgyeFEm2cVT8czhTnDs9QWuOC+DYtAc2w0x8t3fPbeipkyngXbKTOmAsF6fPe3mckgQrAp3eCiLMVnjjuL+/egAQU+Z/+WL4HspEHtAIbl75/7h26/NS5mZsvE8eWGc1hAIaM3FUSZi9WyTYsS1LncGPZ992fxn7YEKG+dUbB6+0JkhpEeZSFf6GQMxtgQyMgngVl+ELdrq2Jj+X4L6VuNwlfJBraTbn1ZtJs04ba1iJ5IKm/nlgyfReCaY32gUvD+bt13uIj1xVUjjuLGkmspBSvFPLdU7orEHXzA0MeZv3ayAw2q6ChrmbN17QpFbEsMFFJxoBgk+FGwlYUXtPdOkLEN/PiVG705zOIdA=
