version: 1.{build}
environment:
  SAUCE_USERNAME:
    secure: MC8R9qcn3YeAxkkdPu1LpO6HivXPNNOs2NrpqQ3/hZc=
  SAUCE_ACCESS_KEY:
    secure: Zsd26FOhSuG6P76uF3hR+XFrgbT7v0+xaqg8ybBrnXnILK5WBESPBmoDcs44vjXi
  matrix:
  - nodejs_version: 4
  - nodejs_version: 5
  - nodejs_version: 6
  - nodejs_version: 7
  - nodejs_version: 8
  - nodejs_version: 9
install:
- cmd: npm install
build: off
test_script:
- cmd: npm run lint && npm run test
- ps: |
    $nodeProcess = start node bin\sc -PassThru
    sleep 5
    if ($nodeProcess.HasExited) { exit 1 }
    Stop-Process -Id $nodeProcess.Id -Force
